### ISSUE TITLE
Error: ResolvePackagesNotFound

### ISSUE THREAD

**Issue by Lynx2102** [CDInstitute/Vitruvio#1]
I am trying to create the given mesh_funcspace environment however when I run the following command to create it: 
conda env create -f environment.yaml
The following packages are not found:
ResolvePackageNotFound:
  - pyembree=0.1.4
  - torchvision=0.2.1
  - pytorch=1.0.0

Is there a way to use another version of the libraries please?

**Comment by albertotono** [comment]
Dear @Lynx2102 , 

Thank you for reaching out, 

I would recommend following the [Readme](https://github.com/CDInstitute/Vitruvio/blob/main/README.md) in this repo, it will point you to the baseline OccNet [here](https://avg.is.mpg.de/publications/occupancy-networks), and their repository is [here](https://github.com/autonomousvision/occupancy_networks). 

for those libraries you can look directly at the Pytorch version / torchvision, you can refer to [this website ](https://pytorch.org/get-started/previous-versions/ ). 

My recommendation is to try to install the latest versions and debug it from there. OccNet is still used [as baseline](https://arxiv.org/pdf/2011.06133). Or trying installing directly via pip. 

I hope it helps.
